FROM node:18 AS builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

RUN npm run build


FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

COPY frontend/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80